### ISSUE TITLE
[Bug]: Previously added videos begin playing with no user interaction even after disablement or removal.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [luisbocanegra/plasma-smart-video-wallpaper-reborn#129]
#### Prerequisites

I have:

1. [x] Searched if this issue hasn't been reported yet.

1. [x] Verified that I am using the latest version (*Wallpaper settings* > *top right corner for version 1.0.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest)**

   > 2.3.0

Install method used:

1. [x] Using Plasma's "Add new widget" (KDE Store)

1. [ ] AUR

1. [ ] Manually from the latest source code

#### **Describe the bug**

When I invoke `plasmashell`, inconsistently, the last played video shall play, even when it isn't added in the configurator, much less enabled.

#### **Steps to reproduce**

1. Add a video, and apply the configuration.

1. Disable or remove all videos, and apply the configuration:

   ![Image](https://github.com/user-attachments/assets/290d7265-8b3a-4a1b-bca5-a7f056563d62)

1. `kquitapp6 plasmashell`

1. `plasmashell`

If that's not clear, see the undermentioned reproduction:

https://github.com/user-attachments/assets/0f75a938-0734-46cf-992a-a100cef1f505

#### **Observed Result**

The last added video plays. With entries added, but disabled, I see:

![Image](https://github.com/user-attachments/assets/421dc63b-a8fa-4511-ab4b-8c4bd02f1f20)

Upon invocation of `plasmashell`, when this reproduces, I see:

<blockquote>

~~~YAML
RokeJulianLockhart@Beedell:~$ plasmashell
kf.plasma.quick: Applet preload policy set to 1
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:178:25: QML FolderViewDropArea (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth":
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:201:9
Toolbox not loading, toolbox package is either invalid or disabled.
qt.multimedia.ffmpeg: Using Qt multimedia with FFmpeg version 7.1.1 GPL version 3 or later
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
Input #0, avi, from '/home/RokeJulianLockhart/Documents/@{'Name'='KCMs'}#.dir/@{'Name'='Wallpaper'}#.dir/@{'Name'='Videography'}#.dir/@{'Name'='Jared'}#.AVI':
  Metadata:
    software        : Lavf61.1.100
  Duration: 00:02:11.24, start: 0.000000, bitrate: 1411449 kb/s
  Stream #0:0: Video: utvideo (ULH0 / 0x30484C55), yuv420p(bt709/unknown/unknown), 2560x1440, 1409979 kb/s, 120 fps, 120 tbr, 120 tbn
  Stream #0:1: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 2 channels, s16, 1536 kb/s
file:///home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/code/utils.js:24: Error: Invalid write to global property "filename"
file:///home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/FadePlayer.qml:161: TypeError: Cannot read property 'filename' of undefined
file:///home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/FadePlayer.qml:160: TypeError: Cannot read property 'playbackRate' of undefined
file:///home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/code/utils.js:24: Error: Invalid write to global property "filename"
qml: RESTORE LAST POSITION: 81813
qt.multimedia.playbackengine.codec: "No HW decoder found"
file:///usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/main.qml:310:13: QML Image: Cannot open: file:///usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/start-here
org.kde.plasma.kicker: Entry is not valid "org.kde.kontact.desktop" 0x55f456706bf0
org.kde.plasma.kicker: Entry is not valid "org.kde.kontact.desktop" 0x55f456706bf0
org.kde.applets.brightness: D-Bus action "KeyboardBrightnessControl" is not available at service "org.kde.Solid.PowerManagement"
~~~

</blockquote>

#### **Expected Result**

Nothing should play:

1. Without entries:

   ![Image](https://github.com/user-attachments/assets/3fd52976-d8f5-40b8-a392-c5d69dc193c5)

1. With entries added, but disabled:

   <details>

   ![Image](https://github.com/user-attachments/assets/41476ebe-9dd4-495d-b694-87d5ab632b63)

   </details>

Were this correct behaviour, the error would not render:

![Image](https://github.com/user-attachments/assets/f83e0dc8-cff5-44ef-b72e-a419030b4e0b)

That's how I knew something was wrong in the add-on, rather than my configuration.

#### **System information**

1. [x] Run `kinfo` on a terminal and paste the output bellow

   `kcmshell6 kcm_about-distro` (`kinfo` is limited) returns:

   <blockquote>

   ~~~YAML
   Operating System: Fedora Linux 42
   KDE Plasma Version: 6.3.5
   KDE Frameworks Version: 6.14.0
   Qt Version: 6.9.0
   Kernel Version: 6.14.6-300.fc42.x86_64 (64-bit)
   Graphics Platform: Wayland
   Processors: 12 × AMD Ryzen 5 7600X 6-Core Processor
   Memory: 30.4 GiB of RAM
   Graphics Processor 1: AMD Radeon RX 5700
   Graphics Processor 2: AMD Radeon Graphics
   ~~~

   </blockquote>

1. [x] Things in your system that might be relevant: [e.g. Kwin scripts, Themes, Addons]

   I've no KWin scripts, and I'm using `org.kde.breezedark.desktop`.

#### **Additional context**

1. I've also had this occur whilst I was writing this, without having restarted `plasmashell`, so IDK what the true cause is.

1. Noticed whilst reproducing https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/102#issuecomment-2902414768, since it, all by itself, began re-showing the image as my background! That is quite serious.

**Comment by RokeJulianLockhart** [comment]
> Hi, how easy is/was this to reproduce for you? I tried the steps provided but was unable to replicate.

@luisbocanegra, I've managed to reproduce it first time. I *think* it's 100% reproducible:

https://github.com/user-attachments/assets/0d8c21c6-53f0-4779-8e4c-adfd76c84360

<details>

<blockquote>

~~~MA
plasmashell
kf.plasma.quick: Applet preload policy set to 1
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:178:25: QML FolderViewDropArea (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth":
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:201:9
Toolbox not loading, toolbox package is either invalid or disabled.
qt.multimedia.ffmpeg: Using Qt multimedia with FFmpeg version 7.1.1 GPL version 3 or later
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
file:///home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/code/utils.js:24: Error: Invalid write to global property "filename"
file:///home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/FadePlayer.qml:161: TypeError: Cannot read property 'filename' of undefined
file:///home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/FadePlayer.qml:160: TypeError: Cannot read property 'playbackRate' of undefined
file:///home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/code/utils.js:24: Error: Invalid write to global property "filename"
Input #0, avi, from '/home/RokeJulianLockhart/Documents/@{'Name'='KCMs'}#.dir/@{'Name'='Wallpaper'}#.dir/@{'Name'='Videography'}#.dir/@{'Name'='Jared'}#.AVI':
  Metadata:
    software        : Lavf61.1.100
  Duration: 00:02:11.24, start: 0.000000, bitrate: 1411449 kb/s
  Stream #0:0: Video: utvideo (ULH0 / 0x30484C55), yuv420p(bt709/unknown/unknown), 2560x1440, 1409979 kb/s, 120 fps, 120 tbr, 120 tbn
  Stream #0:1: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 2 channels, s16, 1536 kb/s
qml: RESTORE LAST POSITION: 0
qt.multimedia.playbackengine.codec: "No HW decoder found"
file:///usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/main.qml:310:13: QML Image: Cannot open: file:///usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/start-here
org.kde.plasma.kicker: Entry is not valid "org.kde.kontact.desktop" 0x5637a131da40
org.kde.plasma.kicker: Entry is not valid "org.kde.kontact.desktop" 0x5637a131da40
org.kde.applets.brightness: D-Bus action "KeyboardBrightnessControl" is not available at service "org.kde.Solid.PowerManagement"
qrc:/qt/qml/org/kde/kirigami/dialogs/PromptDialog.qml:135: TypeError: Cannot read property 'Success' of undefined
qrc:/qt/qml/org/kde/kirigami/dialogs/PromptDialog.qml:97: TypeError: Cannot read property 'None' of undefined
file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml:130: TypeError: Cannot read property 'screenGeometry' of null
file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml:260: TypeError: Cannot read property 'plasmoid' of undefined
file:///home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/main.qml:198: TypeError: Cannot read property 'screenGeometry' of null
QProcess: Destroyed while process ("/home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/tools/gdbus_get_signal.sh") is still running.
~~~

</blockquote>

</details>

Luckily, cloning `main` (`74bec1c572c4cbe1fafc89ebdadddb2500d27665`), as you advised:

<blockquote>

~~~YAML
RokeJulianLockhart@Beedell:~/Documents/UnsanitisedGitRepositories/SVW$ git clone https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn.git
cd plasma-smart-video-wallpaper-reborn
kpackagetool6 -t Plasma/Wallpaper -u package/
Cloning into 'plasma-smart-video-wallpaper-reborn'...
remote: Enumerating objects: 1048, done.
remote: Counting objects: 100% (365/365), done.
remote: Compressing objects: 100% (162/162), done.
remote: Total 1048 (delta 237), reused 266 (delta 194), pack-reused 683 (from 1)
Receiving objects: 100% (1048/1048), 4.12 MiB | 3.41 MiB/s, done.
Resolving deltas: 100% (516/516), done.
Upgrading package from file: /home/RokeJulianLockhart/Documents/UnsanitisedGitRepositories/SVW/plasma-smart-video-wallpaper-reborn/package
Successfully upgraded /home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/
RokeJulianLockhart@Beedell:~/Documents/UnsanitisedGitRepositories/SVW/plasma-smart-video-wallpaper-reborn$ kquitapp6 plasmashell && plasmashell
~~~

</blockquote>

...I don't appear to be able to reproduce it anymore:

https://github.com/user-attachments/assets/fa4fe2b5-b0ea-430e-bcaf-987769b6f310

For comparison, I removed PSVW, and re-installed 2.3.0 from the KDE Store via Discover. I was immediately able to reproduce it again. When I ran a `git diff --no-index $release_file $main_file --unified=0 > diff.diff` on the copies of `$HOME/.config/plasma-org.kde.plasma.desktop-appletsrc`, copied whilst I'd run the release and `main` versions, I saw:

<blockquote>

~~~diff
@@ -108 +108 @@ wallpaperplugin=luisbocanegra.smart.video.wallpaper.reborn
-DialogHeight=704
+DialogHeight=555
@@ -124,3 +123,0 @@ VideoUrls=[{"filename":"file:///home/RokeJulianLockhart/Documents/@%7B'Name'='KC
-[Containments][33][Wallpaper][org.kde.color][General]
-Color=29,153,243
-
~~~

</blockquote>

I can't imagine that any of *that* matters. Anyway, using the problematic version, it's:

<blockquote>

~~~desktop
[Containments][33][Wallpaper][luisbocanegra.smart.video.wallpaper.reborn][General]
BlurMode=1
CrossfadeEnabled=true
MuteMode=2
VideoUrls=[{"filename":"file:///home/RokeJulianLockhart/Documents/@%7B'Name'='KCMs'%7D%23.dir/@%7B'Name'='Wallpaper'%7D%23.dir/@%7B'Name'='Videography'%7D%23.dir/@%7B'Name'='Jared'%7D%23.AVI","enabled":false,"duration":0,"customDuration":0,"playbackRate":0}]
~~~

</blockquote>

**Comment by luisbocanegra** [comment]
Thanks for the confirmation, it seems it indeed was https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/commit/eda07864bfa1a817d3fe345f134c57f08976e143 and you machine being able to pick the videos before they where filtered. I guess either yours is too fast or mine is just so bloated it wasn't able to start playback that soon for me to notice 😅

**Comment by RokeJulianLockhart** [comment]
This continues to affect 2.3.2, for the video added, but disabled, returns:

<p></p>

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/aefbc766-bb1e-4577-8c23-72a5aa31c331" />

<p></p>

#### Diagnosis

Upon enablement, I have observed:

<blockquote>

~~~MA
19:00:20 plasmashell[2239]: file:///home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/config.qml:164:17: QML TextField: Binding loop detected for property "text":
                            file:///home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/config.qml:165:21
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml:205: Error: Cannot assign to non-existent property "wallpaperConfiguration"
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml:205: Error: Cannot assign to non-existent property "configDialog"
19:00:20 kernel: amdgpu 0000:59:00.0: [drm] Cannot find any crtc or sizes
19:00:20 plasmashell[2239]: file:///home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/config.qml: Setting initial properties failed: FormLayout does not have a property called wallpaperConfiguration
19:00:20 plasmashell[2239]: file:///home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/config.qml: Setting initial properties failed: FormLayout does not have a property called configDialog
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_viewModeDefault
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_viewMode
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_useCustomIconD>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_useCustomIcon
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_urlDefault
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_url
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_toolTipsDefault
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_toolTips
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_textLinesDefau>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_textLines
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_textColorDefau>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_textColor
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_sortModeDefault
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_sortMode
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_sortDirsFirstD>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_sortDirsFirst
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_sortDescDefault
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_sortDesc
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_showHiddenFile>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_showHiddenFiles
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_selectionMarke>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_selectionMarke>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_renameInlineDe>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_renameInline
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_previewsDefault
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_previews
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_previewPlugins>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_previewPlugins
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_positionsDefau>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_positions
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_popupsDefault
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_popups
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_lockedDefault
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_locked
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_labelWidthDefa>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_labelWidth
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_labelTextDefau>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_labelText
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_labelModeDefau>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_labelMode
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_iconSizeDefault
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_iconSize
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_iconDefault
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_icon
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_filterPatternD>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_filterPattern
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_filterModeDefa>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_filterMode
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_filterMimeType>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_filterMimeTypes
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_arrangementDef>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_arrangement
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_alignmentDefau>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_alignment
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_ToolBoxButtonY>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_ToolBoxButtonY
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_ToolBoxButtonX>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_ToolBoxButtonX
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_ToolBoxButtonS>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_ToolBoxButtonS>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_ItemsGeometrie>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_ItemsGeometries
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_FirstStartupDe>
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml: Setting initial properties failed: ConfigurationContainmentAppearance does not have a property called cfg_FirstStartup
19:00:20 plasmashell[2239]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml:19:1: QML ConfigurationContainmentAppearance: Created graphical object was not placed in the graphics scene.
~~~

</blockquote>

...whereas, upon disablement:

<blockquote>

~~~MA
19:01:02 plasmashell[2239]: file:///home/RokeJulianLockhart/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/main.qml:168: TypeError: Value is undefined and could not be converted to an object
~~~

</blockquote>

**Comment by luisbocanegra** [comment]
> The entire video playlist / order doesn't work for me.

Is the change wallpaper option in slideshow mode?

> If I disable or reorder things, it keeps playing the old video. If I disable all it stops, if I enable a different video it still plays the old one. It's just completely borked.

Order changes take effect only after the current video has been played

> if I enable a different video it still plays the old one.

Okay this one is a bug, it should switch to the other single video but it doesn't, might be related to this bug, seems trivial to fix, will do that for the next version.

> Also, the individual loop function mentions a "next video" function to skip to the next one, but I can't find any info on what that is or how to use it.

The option should be in the desktop right-click menu when there two or more videos in the list, If it's not there please create another bug report using the bug template: https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/new?template=bug_report.md


<img width="423" height="312" alt="Image" src="https://github.com/user-attachments/assets/98648ed2-2c0e-466d-b5f3-8e59c67bbe7e" />

**Comment by Dark-Thoughts** [comment]
> You might want to try switching to gstreamer as video back-end as described here

I'd rather not do any more system level config stuff because I already can't get my system into sleep / standby anymore because of that either.

> can you share your system information?

```
Operating System: Bazzite 43
KDE Plasma Version: 6.5.1
KDE Frameworks Version: 6.19.0
Qt Version: 6.10.0
Kernel Version: 6.17.7-ba01.fc43.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700X3D 8-Core Processor
Memory: 32 GiB of RAM (31.3 GiB usable)
Graphics Processor: AMD Radeon RX 6650 XT
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B550M DS3H
System Version: Default string-CF
```

> Hmm it is there, I think the wording could use some improvement

That's not where I saw it, but on the individual file settings, which does not mention that:

<img width="474" height="215" alt="Image" src="https://github.com/user-attachments/assets/9f5bfb83-6ea7-4cb0-9a35-02ce00c9efec" />

> Yes, I plan to improve the UI/UX a bit as part of [#180](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/180) let me know in that issue if you have any suggestions on how could we implement that.

Like I said, a "play" button in the video list where you also sort & remove the individual videos would be helpful, imo.

**Comment by RokeJulianLockhart** [comment]
Might this conversation be better in a separate discussion, or have I misunderstood? It seems like it hasn't much been related to *this* issue, per se, since [`#issuecomment-3522117680`](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/129#issuecomment-3522117680).

**Comment by luisbocanegra** [comment]
Done, https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/181 sorry for the noise

**Comment by RokeJulianLockhart** [comment]
@luisbocanegra, something *similar* still persists:

<p></p><img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/ea1e83c6-fa38-48f0-afd2-441089505c70" /><p></p>

*That* was an instance of the wallpaper returning upon removal, which required reinitialisation of the plugin to remediate. I've not, yet, sufficient information to create a new report, I believe.
